server:
  port: 8089

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://192.168.11.102:3306/leyou?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 1000
      test-on-borrow: true
  rabbitmq:
    host: 192.168.11.101
    username: leyou
    password: 123
    virtual-host: /leyou
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 300000ms
        multiplier: 2
      exchange: ly.item.exchange
    publisher-confirms: true
  redis:
    host: 192.168.11.101
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10

mybatis:
  type-aliases-package: com.leyou.item.pojo
  mapper-locations: mapper/OrderMapper.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  not-empty: false
  identity: mysql
ly:
  worker:    #创建idWorker对象的配置
    workerId: 1        #当前机器id
    datacenterId: 1    #序列号
  jwt:
    pubKeyPath: D:/ideaWorkPlace/leyou-city/rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  pay:
    appId: wx8397f8696b538317    #公众账号id
    mchId: 1473426802            #商户id
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb    #微信提供的生成签名的密钥
    connectTimeoutMs: 5000
    readTimeoutMs: 10000
    notifyUrl: http://www.leyou.com/notify/pay      #微信支付成功后微信回调的自己后台的接口
