server:
  port: 8086

spring:
  application:
    name: sms-service
  rabbitmq:
    password: admin
    username: admin
    host: 192.168.100.205

leyou:
  sms:
    accessKeyId: JWffwFJIwada # 你自己的accessKeyId
    accessKeySecret: aySRliswq8fe7rF9gQyy1Izz4MQ # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_133976814 # 模板名称